repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(README.md|CONFIG.md)
  - id: end-of-file-fixer
  - id: debug-statements
  - id: requirements-txt-fixer
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
    args: [--py38-plus, --add-import, 'from __future__ import annotations']
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.8
